var plaatsnamen = new Array("Drachten", "Leeuwarden", "Dokkum", "Burgum", "Garyp", "Heerenveen", "Feanwâlden", "Wolvega", "Aldeboarn", "Joure", "Oosterwolde")
document.write("<p> Plaatsen Array: "+  plaatsnamen+ "</p>")
document.write("<br>")
plaatsnamen.splice(5,1)
document.write("<p> Plaatsen Array zonder heerenveen: "+  plaatsnamen+ "</p>")
document.write("<br>")
plaatsnamen.pop()
document.write("<p> Plaatsen Array zonder de laatste: "+  plaatsnamen+ "</p>")
document.write("<br>")
var plaatsnamen = new Array("Drachten", "Leeuwarden", "Dokkum", "Burgum", "Garyp", "Heerenveen", "Feanwâlden", "Wolvega", "Aldeboarn", "Joure", "Oosterwolde")
plaatsnamen.splice(2,0, "Hurdegaryp")
document.write("<p> Plaatsen Array met Hurdegaryp: "+  plaatsnamen+ "</p>")
document.write("<br>")
plaatsnamen.unshift("Ferwert","Kollum","Surhuisterveen")
document.write("<p> Plaatsen Array met Ferwert, Kollum en Surhuisterveen: "+  plaatsnamen+ "</p>")
document.write("<br>")
plaatsnamen.push("Donkerbroek","Boornbergum")
document.write("<p> Plaatsen Array met Donkerbroek en Boornbergum: "+  plaatsnamen+ "</p>")
document.write("<br>")
plaatsnamen.sort()
document.write("<p> Plaatsen Array in volgorde: "+  plaatsnamen+ "</p>")
document.write("<br>")
plaatsnamen.reverse()
document.write("<p> Plaatsen Array in reverse: "+  plaatsnamen+ "</p>")
document.write("<br>")